-- ─── Seed：現有 GitHub Pages（external 類型）─────────────────
-- 這些是 quiz.urland.com.tw 上的舊靜態頁面
-- page_type = 'external'，migration_status = 'legacy'

INSERT INTO landing_pages (name, slug, page_type, external_url, migration_status, status)
VALUES
  (
    '主場水域自測',
    'waterzone',
    'external',
    'https://quiz.urland.com.tw/waterzone/',
    'legacy',
    'published'
  ),
  (
    '抓住他的心',
    'catch',
    'external',
    'https://quiz.urland.com.tw/catch/',
    'legacy',
    'published'
  ),
  (
    '約會測驗',
    'dating',
    'external',
    'https://quiz.urland.com.tw/dating/',
    'legacy',
    'published'
  ),
  (
    '家庭測驗',
    'familyquiz',
    'external',
    'https://quiz.urland.com.tw/familyquiz/',
    'legacy',
    'published'
  ),
  (
    '下一步',
    'nextstep',
    'external',
    'https://quiz.urland.com.tw/nextstep/',
    'legacy',
    'published'
  ),
  (
    '邊界清單',
    'checklist',
    'external',
    'https://quiz.urland.com.tw/checklist/',
    'legacy',
    'published'
  ),
  (
    '親子界限',
    'parent-boundary',
    'external',
    'https://quiz.urland.com.tw/parent-boundary/',
    'legacy',
    'published'
  ),
  (
    '路徑測驗',
    'path',
    'external',
    'https://quiz.urland.com.tw/path/',
    'legacy',
    'published'
  ),
  (
    '系統測驗',
    'system',
    'external',
    'https://quiz.urland.com.tw/system/',
    'legacy',
    'published'
  ),
  (
    '日曆',
    'calendar',
    'external',
    'https://quiz.urland.com.tw/calendar/',
    'legacy',
    'published'
  ),
  (
    '掃描',
    'scan',
    'external',
    'https://quiz.urland.com.tw/scan/',
    'legacy',
    'published'
  ),
  (
    '卡住的伴侶',
    'couples-stuck',
    'external',
    'https://quiz.urland.com.tw/couples-stuck/',
    'legacy',
    'published'
  ),
  (
    '邊界',
    'border',
    'external',
    'https://quiz.urland.com.tw/border/',
    'legacy',
    'published'
  ),
  (
    'FB App',
    'fb-app',
    'external',
    'https://quiz.urland.com.tw/FB_app/',
    'legacy',
    'published'
  ),
  (
    '產生器',
    'generator',
    'external',
    'https://quiz.urland.com.tw/generator/',
    'legacy',
    'published'
  )
ON CONFLICT (slug) DO NOTHING;
